mechanicalsoup/browser.py

Allow file objects as values of <input type=file>

---

mechanicalsoup/browser.py

Deal with [Issue#15](https://github.com/hickford/MechanicalSoup/issues/15)

Customize soup

---

.travis.yml
README.md

PyPy3 also passes, so if you want, this includes tests and support for it.
Also includes PR #44.

Add support for PyPy3

---

mechanicalsoup/form.py
mechanicalsoup/utils.py
tests/test_form.py

Two minor fixes extracted from #53. Should be rather uncontroversial.

Minor Fixes

---

MANIFEST.in

Include examples to the release tarball

---

example.py
mechanicalsoup/browser.py
mechanicalsoup/stateful_browser.py
tests/test_browser.py
tests/test_stateful_browser.py

Ported from chamilotools (new tests added).

*browser.py: allow raising LinkNotFound on 404 error

---

mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

Replicate previous mechanize facility of being able to pass in a link

---

docs/conf.py
mechanicalsoup/__init__.py
mechanicalsoup/__version__.py
setup.py

Modelled after how requests library does it.

Single place to set version number

---

README.md
mechanicalsoup/browser.py
tests/test_browser.py
tests/test_stateful_browser.py

As discussed in https://github.com/hickford/MechanicalSoup/issues/77

Add ability to edit user agent

---

mechanicalsoup/browser.py
mechanicalsoup/form.py
tests/test_form.py

E.g. multiple buttons here: https://dtdportal.atocrsp.org/

choose_submit ignored <button> element

---

tests/test_browser.py
tests/test_stateful_browser.py

Add some unit tests to show improvement in code coverage.

More tests

---

tests/test_form.py

Test that a `<select>` element (i.e. dropdown) has the correct
option selected by `Form.set`.
Generalize `setup_mock_browser` so that it can be used for more than
just multi-button forms (and use it in this test).

test_form.py: add test of select branch of Form.set

---

README.md
tests/setpath.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py

Update sys.path in tests and update README following recent changes.

Path and readme

---

docs/ChangeLog.rst
docs/tutorial.rst
examples/expl_httpbin.py
mechanicalsoup/form.py
tests/test_form.py

While trying to write small examples, this turned out to be really
something the user (=me) needs and appreciates.

form: add print_summary() method

---

docs/ChangeLog.rst

I think this fix is what you meant, but making a PR just in case!

ChangeLog.rst: fix typo

---

docs/tutorial.rst

sumbit button -> submit button

corrected minor typo

---

mechanicalsoup/stateful_browser.py

This is a simple data structure that holds the page, url, and form.
It makes managing the state of the StatefulBrowser much easier.
-------------
I'm doing some work on adding a `download` method, and having an easier way to manage the state of the browser is a useful prerequisite.

stateful_browser.py: add internal _BrowserState class

---

docs/ChangeLog.rst
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

The same is done for `download_link` in PR #182.

Set the Referer header in follow_link and submit_selected

---

docs/ChangeLog.rst
mechanicalsoup/browser.py
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

This is my proposal for `download_link`, it superseeds #182 (I created a new PR to avoid force-pushing to a branch which is not mine).

stateful_browser.py: add download_link method

---

docs/external-resources.rst

@amotl: do you mind if we add your tool to our "using MechanicalSoup" list?

Add PatZilla to tools using MechanicalSoup

---

docs/ChangeLog.rst
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py
tests/utils.py

I started to implement the page refresh functionality as described in #187. Basically, I added the request to the `_BrowserState` and using it to resend the last request.
Before implementing any tests (so coverage is currently down), I would like to get some feedback whether I missing something or anything is not correctly implemented.

Page refresh

---

mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

Fixes #169.
Please let me know if I have missed something or done anything wrong.

allow passing bs4.element.Tag object to select_form func

---

docs/ChangeLog.rst
mechanicalsoup/stateful_browser.py

* Update changelog
* Minor code logic cleanup from recent referer and select_form changes

Final changes in preparation for 0.10 release

---

mechanicalsoup/browser.py

Old link was not working anymore, replaced it with a new one.

Fixed a broken link

---

docs/faq.rst

This answers the question of what to do when form submission
fails due to the website using JavaScript.

faq.rst: address common Stack Overflow question

---

CONTRIBUTING.rst
README.rst

Closes #202.
LGTM (Looks Good To Me) is an automated code review tool that
reports to be able to uncover both simple and complex issues.
--------------------
I feel like the "Alerts" badge is useless unless you know what LGTM is, and the "Grade" badge is useless if you _do_ know what LGTM is, so I added both badges to be safe. I'm happy keeping both or choosing just one.

Add LGTM badges

---

tests/requirements.txt

Hi,
Tests fail with requests_mock 1.2.0. I've run git bisect and found out that the first working commit is https://github.com/jamielennox/requests-mock/commit/10c84747e09295eecdc0513eed9392283174d126.
Otherwise the following failure can be seen:
```
running pytest
Searching for pytest-flake8
Best match: pytest-flake8 1.0.1
Processing pytest_flake8-1.0.1-py3.6.egg
Using /tmp/MechanicalSoup/.eggs/pytest_flake8-1.0.1-py3.6.egg
Searching for pytest-cov
Best match: pytest-cov 2.5.1
Processing pytest_cov-2.5.1-py3.6.egg
Using /tmp/MechanicalSoup/.eggs/pytest_cov-2.5.1-py3.6.egg
Searching for pytest>=3.5
Best match: pytest 3.6.2
Processing pytest-3.6.2-py3.6.egg
Using /tmp/MechanicalSoup/.eggs/pytest-3.6.2-py3.6.egg
Searching for flake8>=3.5
Best match: flake8 3.5.0
Processing …
```

Require requests_mock>=1.3.0, otherwise some tests fail

---

docs/ChangeLog.rst

@moy Once you approve this final changelog, I will begin the release procedures for v0.11.

ChangeLog.rst: final changelog before release

---

CONTRIBUTING.rst

Add extra detail about how to specify version numbers and about
creating the release branch.

CONTRIBUTING.rst: Update release instructions

---

mechanicalsoup/browser.py
mechanicalsoup/form.py
tests/test_browser.py
tests/test_form.py

Fixes #245. It was actually a bit more involved than just adding a `.lower()` in the code, since there are several places where we look for radio and checkboxes.

Case insensitive type="radio" and type="checkbox"

---

docs/faq.rst

mechanize is back on track, RoboBrowser seems clearly abandonned.

FAQ: Update on alternatives

---

README.rst
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

This patch addresses a few omissions from #294.

Update a few missed instances of deprecated methods

---

.travis.yml
docs/ChangeLog.rst
setup.py

No source code changes needed.

Add support for Python 3.8

---

examples/expl_duck_duck_go.py

* Revert the incorrect selector change in #315 
* Add a custom user agent so that, when we submit the form, we get a results page instead of an error.

Fix expl_duck_duck_go.py once and for all

---

.travis.yml
docs/ChangeLog.rst
setup.py

Add support for Python 3.9

---

mechanicalsoup/browser.py
tests/test_browser.py

I have to use PUT method in a personnal project, but it was not exposed.
Tests passed in my env.

Add a wrapper to PUT

---

mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

Add support for no button to `StatefulBrowser.submit_selected`

---

.github/workflows/python-package.yml
docs/ChangeLog.rst
setup.py

Python 3.11 was released on 2022-10-24.

Add support for Python 3.11

---

setup.py

The real solution would be to move to a more modern packaging system like Poetry, but waiting for this to happen we should at least parse properly our own requirement file.

Actually deal with comments in requirements.txt
