setup.py

`Session.prepare_request` was added in [*requests 2.0.0*](https://pypi.python.org/pypi/requests#id24). So this version should be ensured in *setup.py*.
This bit me on an old system with an old version of *requests* already installed.

Require requests >= 2.0 in setup.py

---

mechanicalsoup/browser.py
mechanicalsoup/form.py

This fixes the library to correctly handle the following scenarios:
- The `"method"` attribute of a form may be left unspecified, in which case it defaults to GET.
- The `"action"` method of a form may be left unspecified, in which case it should be the URL of the source document, which in this case is (assumed to be) the `url` argument to `submit`.  (If both `"action"` and `url` are undefined, raise an error.)
- When submitting form data via GET, the data should be passed to `requests` in the `params` argument, not `data`.
Also fixed a couple minor coding things.

Handle empty "method" & "action" and submit via GET correctly

---

mechanicalsoup/browser.py

Fixes for two bugs found when trying to submit Django user change form:
* #26 multi-value selects
* #27 radio/checkboxes with no 'value' provided
The whole function could probably be refactored to always use lists of values, but I decided to keep most of the code and behaviour unchanged.

Form submission fixes

---

mechanicalsoup/browser.py

This change will make us able to implement custom transport adapter, increasing possibilities of connection customization.
It's possible to pass to `Browser()` a dict containig the adaptee as key, and the adapter itself as value.
(see for reference: http://docs.python-requests.org/en/latest/user/advanced/#transport-adapters)

added requests's custom adapter implementation

---

README.md

A version of PyPI badge is incorrect.
| Before | After |
|-----|----|
| <img width="342" alt="2016-06-11 23 35 51" src="https://cloud.githubusercontent.com/assets/532251/15985579/87e37994-302d-11e6-9be2-1a4552400259.png"> | <img width="270" alt="2016-06-11 23 36 59" src="https://cloud.githubusercontent.com/assets/532251/15985580/8ebfdfa0-302d-11e6-92d3-1771ac8ea648.png"> |

Fix incorrect PyPI version badge

---

.travis.yml
README.md

[Requests docs](http://docs.python-requests.org/en/master/) say:
> Requests officially supports Python 2.6–2.7 & 3.3–3.5, and runs great on PyPy.
This caused [3.2 to fail for MechanicalSoup](https://travis-ci.org/hickford/MechanicalSoup/builds/155249108) too, so remove support for it.

Requests no longer supports 3.2

---

mechanicalsoup/browser.py

In Python2, the method obtained from BeautifulSoup is a Unicode string,
and passing it to requests causes encoding issues when used together
with the files argument:
```
File "/usr/local/lib/python2.7/dist-packages/requests-2.3.0-py2.7.egg/requests/sessions.py", line 559, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests-2.3.0-py2.7.egg/requests/adapters.py", line 327, in send
timeout=timeout
File "/usr/local/lib/python2.7/dist-packages/requests-2.3.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
body=body, headers=headers)
File "/usr/local/lib/python2.7/dist-packages/requests-2.3.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 291, in _make_request
conn.request(method, url, **httplib_request_kw) …
```

submit(): make sure method is an str

---

mechanicalsoup/browser.py

For debugging, it's very convenient to be able to fire up a browser on
the current page.

browser: add a launch_browser method

---

example.py

ea5e675 (update example.py, 2015-06-30) introduced a bunch of
improvements to example.py, and most of these changes were accidentally
reverted by 4907e63 (Merge branch 'Xuefeng-Zhu-example', 2015-11-24).
In particular, the original commit introduced the creation of a
mechanicalsoup.Form() object based on a beautiful soup one, and this
change is needed for the code to work. Without this, one tries to call
method input() on a soup object instead of using the mechanicalsoup one.
Fixes #40.

example.py: restore changes lost by bad merge

---

example.py
example_manual.py
mechanicalsoup/__init__.py
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py

This PR is the result of moving code from https://gitlab.com/chamilotools/chamilotools to MechanicalSoup.
The two main features are:
* StatefulBrowser, which keeps track of the current URL, page and form for you.
* The ability to write `form["name"] = value` instead of form.{check,input,textarea}.
* Because the StatefulBrowser keeps track of the current form, we can even write `browser["name"] = value` instead of `form["name"] = value`.
See what it allows in the new [example.py](https://github.com/moy/MechanicalSoup/blob/stateful-browser/example.py). The main part is
```Python
browser.open("https://github.com")
browser.follow_link("login")
browser.select_form('#login form')
browser["login"] = args.username
browser["password"] = args.password
resp = browser.submit_selected()
```
It could …

New features (stateful browser, __setitem__, ...) from chamilotools

---

MANIFEST.in

Linux distributions usually source themselves from PyPI, as it is currently the case for the [Debian package](https://packages.debian.org/source/sid/python-mechanicalsoup). The source tarball is currently missing the test suite (for CI purposes), the licensing terms governing the distribution (LICENSE file) and some form of documentation (README.md file).
You might want to distribute the examples as well, if so just add a new line with `include example*.py`).

Improve content of source tarball

---

example.py
example_manual.py

It's really bad practice to let the system decide which parser to use:
it encourages people to write scripts that will behave differently on
different machines, depending on which parser is installed.
example.py does work with lxml, but not with html.parser for example,
hence the example is broken on machines where html.parser is available
but lxml is not.
Fix this by specifying the parser explicitly.
IMHO, this is the proper fix to the issue raised by PR #67.

example.py: specify parser explicitly

---

README.md

I found the https://github.com/hickford/MechanicalSoup#development section a bit sparse.
If you've got a 'dev' version of mechanicalsoup and a system installed one that is maybe being used by other projects, it's not clear how to test the dev version separately, or how to test against multiple versions of Python.  Also, running `py.test` inside a .virtualenv didn't work for me as that looks at the system wide version I think.

Instructions on how to setup virtualenv for both Python2 & Python3

---

mechanicalsoup/browser.py
tests/test_stateful_browser.py

The previous implementation of user_agent only set the user_agent
for requests created with `Browser._build_request`. However, there
are many other methods in `Browser` that make requests, and these
did not use the specified user_agent.
The `test_user_agent` function is added to show the failure
scenario. To fix this, we set user_agent for the session owned by
`Browser`, so that all requests use the specified user_agent.

Apply user_agent to all session requests

---

.gitignore

These are created as byproducts of the recommended
development workflow.

.gitignore: ignore virtualenv directories

---

mechanicalsoup/browser.py
tests/test_browser.py

* The `Browser.{set,get}_cookie` methods provide a way to set and
get the requests cookiejar without needing to know the details
of the requests module.
* Improve consistency with mechanize, which also provides a
`Browser.set_cookie` method.

browser.py: add a direct interface to the cookiejar

---

mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

The `StatefulBrowser.open_relative` method took additional args
and kwargs, but did not forward them to `StatefulBrowser.open`.
This resulted in these additional arguments being ignored.
In this patch, we now forward the arguments correctly and add
a unit test of `open_relative`.

Fix argument forwarding of `open_relative`

---

tests/test_stateful_browser.py

Add a test of the non-singleton result on a page containing
several links. This was requested in the PR #87 discussion.

test_stateful_browser.py: improve test_links

---

.coveragerc
.travis.yml
README.md
setup.cfg

Use the pytest-cov plugin to do coverage reporting. Running tests
locally with `pytest` will output the report. In the Travis-CI builds,
this report will automatically be uploaded to codecov.io.
Closes #88.
I believe that @hickford will need to create a codecov.io account to set up the integration with Travis-CI and to enable the codecov badge in the README. I know that he already has a coveralls account, but I think codecov.io is the better choice.
See the [codecov.io page for my fork](https://codecov.io/gh/hemberger/MechanicalSoup/tree/85c484d1c2e6513ce67fd25053b37bae6da7c7d0) to see the effects of this PR.

Add code coverage reporting

---

.travis.yml
README.md
setup.py

Python 2.6 has been at end-of-life as of 2013-10-29, and 3.3 has one day left, until 2017-09-29.
https://snarky.ca/stop-using-python-2-6/

Drop unsupported Python 2.6 and 3.3

---

.travis.yml

The `coverage` executable needs to exist in the environment for the
Codecov uploader to work correctly. Therefore, it is insufficient to
install `pytest-cov` (which provides `coverage`) with `tests_require`
in setup.py.
This fixes the "Python coveragepy not found" error output by the
uploader after the change to the Travis-CI environment in b3232dd.

Fix Travis-CI coverage report uploading

---

.travis.yml
README.md
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
setup.cfg
setup.py

We can avoid the manual step of running flake8 by integrating it
into the test suite with the pytest-flake8 plugin.
This PR also fixes a few flake8 warnings.

Run flake8 with pytest

---

README.md
example.py
example_manual.py
mechanicalsoup/__version__.py

We have moved to the `MechanicalSoup` organization, so we need to
update the repository URL in the examples, documentation, and badges.
No functionality changes.

Update repository URL

---

README.md

The dependencies listed in the README for the development environment
have become outdated. This is because a) we are no longer necessarily
installing the package before running tests and b) some new machinery
is used in the test suite.

README.md: update development dependencies

---

.codecov.yml

The Codecov PR comments are too verbose and do not add anything that
the Codecov GitHub App does not provide in the integrated checks.

.codecov.yml: disable PR comments

---

README.md

Use the PyPI badge to display which Python versions are supported in
the latest PyPI release version. Previously, Python version support
identified the version supported in the current master branch, but
these two are not necessarily the same.
Provide instructions for developers to see the Python version support
in the current master branch so that we do not need to hard-code the
version list in more places (it's already hard-coded in two places:
`setup.py` and `.travis.yml`).
NOTE: I'm open to hard-coding this list in the README instead of providing a programmatic method if you think it would be more useful. We'll just need to be vigilant about desync. :)

README.md: more precise python version info

---

mechanicalsoup/browser.py

The AttributeError except was implemented for versions of `requests`
that did not have a `utils.default_user_agent` method. However, we
require `requests >= 2.0`. Since this method exists in the minimum
required version (2.0), there is no need to keep this exception.
NOTE: Please reject this PR if it is important to handle possible `AttributeError` exceptions _within the implementation_ of `requests.utils.default_user_agent`. While this method existed in v2.0, it still called methods and members of other modules until v2.8.0 (at which point it became a trivial method with no possibility of an `AttributeError`), which could in principle raise an `AttributeError`. For unimpeachable safety, keep the code as-is and reject the PR until we require `requests >= 2.8.0`.

browser.py: don't except AttributeError in set_user_agent

---

README.md
requirements.txt
setup.py
tests/requirements.txt

Addresses issue #109.
Move install and test dependencies out of `setup.py` and into
`requirements.txt` and `tests/requirements.txt` respectively.
To avoid duplicating the list of dependencies, we read these
files in `setup.py` to build the `install_requires` and
`tests_require` lists.
In the development workflow instructions, we can recommend
installing all dependencies with pip using these files to avoid
yet another place where the list of dependencies would otherwise
be duplicated.

Switch to requirements.txt files

---

.mention-bot

I suggest we enable the [mention bot](https://github.com/facebook/mention-bot) to ping contributors when a PR modifies their code. The goal is to encourage occasional contributors to come back in the discussion when their code is modified. 
We don't want to spam hickford, who wrote large parts of the code but is less active these days, nor moy and hemberget who are already watching the project anyway, so this PR adds a blacklist to avoid this.
Opinions?

add .mention-bot configuration file

---

mechanicalsoup/form.py

Instead of storing a bool to detect if we found at least one
item in a list of items that matches a certain criteria,
use the `for-else` language construct, where the `else` is
executed unless we `break` during the for-loop.

form.py: minor simplification in check method

---

docs/ChangeLog.rst
mechanicalsoup/__init__.py
mechanicalsoup/form.py
tests/test_form.py

Instead of having Form.set implement textarea/check/select/input
itself, call the methods that already implement these. This change
reduces code duplication and prevents the two implementations
from getting out of sync (which had already happened with Form.check).
A new exception InvalidFormMethod is derived from LinkNotFoundError
and used in the methods called by Form.set to catch when the method
doesn't apply to the particular element being set. This is how
Form.set does its element type deduction now.
All methods called from Form.set are now prefixed with "set_".
Form.set
* Is now a wrapper around Form.set_*.
* Retains its original behavior.
Form.check
* Is now a wrapper around Form.set_{checkbox,radio}.
* Retains its original behavior for backwards compatibility, even
though its …

form.py: refactor set method

---

setup.cfg

By default, autodoc caches its results in
docs/_build/doctrees/mechanicalsoup.doctree and doesn't regenerate it
when docstrings are modified.
Force a more brutal approach where everything is rebuilt each time.
Fixes #128.

setup.cfg: activate all-files and fresh-env (-a -E)

---

docs/mechanicalsoup.rst
mechanicalsoup/browser.py
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py

In this PR:
* Add missing docstrings
* Improve clarity of existing text
* Add many sphinx function/class links
* Add some sphinx `:param:` or `:return:` docs
* More links to external resources when we use another object's API
Things not in this PR:
* Complete coverage of `:param:` and `:return:` (these can be a bit clunky for simple functions, but we may decide that we want to include them in the end)
* Example code
I think there's still a lot of room for improvement, but it's a good first pass. This also cleans up the internal interface a bit where I noticed areas for improvement while documenting.

Improve docstrings

---

docs/ChangeLog.rst
mechanicalsoup/browser.py
mechanicalsoup/stateful_browser.py

Instead of omitting the soup attribute when the response is not
text/html, set it to None. This has two positive effects:
1. StatefulBrowser can now unconditionally set the current page
from response.soup. We no longer need to remember to handle the
case when response.soup is not set.
2. We fix another hidden bug in StatefulBrowser.open, which is the
same bug @moy recently fixed in StatefulBrowser.submit_selected.
Specifically, when the page is not text/html, we no longer keep
the previous page in memory.

browser.py: add_soup now always attaches a soup

---

CONTRIBUTING.rst
README.rst
docs/ChangeLog.rst

Does it matter if we still use http when connecting to http://httpbin.org for tests? (should we be testing both http and https?)

Prefer https over http in documentation links

---

CONTRIBUTING.rst

I'd like to release a 0.9, if only to get the PyPi page updated (there are not many user-facing changes in the code, even though there's been a real overhaul inside).
In the process of avoiding the single point of failure, I think it would be nice to let @hemberger do it (enjoy your new priviledges ;-) ).
To help with this, here's a list of what I usually do (well, I didn't do the "Update the version number to a ``x.y.dev`` number in ``mechanicalsoup/__version__.py``" step last time, but probably I should have). Not sure CONTRIBUTING.rst is the best place, but I picked this to avoid creating yet-another-file that no one would read.

Release checklist

---

docs/ChangeLog.rst
mechanicalsoup/form.py
tests/test_form.py

Fixes #124.
Normally, only one option of a select element can be selected.
But in a `<select multiple>`, it is valid HTML to select multiple
options.
We now support this with the following syntax:
```python
form.set_select({'name': ('option1', 'option2')})
```

form.py: support <select multiple>

---

docs/faq.rst
mechanicalsoup/browser.py
tests/test_stateful_browser.py

We implement the same methods as request.session, allowing code like
def test_with():
with mechanicalsoup.StatefulBrowser() as browser:
browser.open(url)

browser: implement __enter__ and __exit__

---

setup.cfg
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py

This is mostly whitespace and line-length changes, as well as
a few unused variable fixes.
The tests `test_form_{noname,multiple}` now assert that the
request was successful.
----------------
Currently, the tests do not pass due to line-too-long flake8 errors (E501) in `test_{form,browser}.py`. The offending lines are the html samples. I'm not exactly sure how to handle these errors.

Include tests directory in flake8 tests

---

README.rst
examples/expl_duck_duck_go.py
examples/expl_google.py

Since the example scripts are what people will often look at
to learn how MechanicalSoup works, we want them to be as obvious
as possible. For that reason, rename the loop variables:
'l' -> 'link'

More explicit example variable names

---

mechanicalsoup/form.py

The name `el` was not sufficiently descriptive or clear. Instead,
we name it `submit` because it is the Tag of the submit element
or its name-attribute.
---------------------------
We are deciding whether or not to make this change, because it could in theory break backwards compatibility if someone were to have written `choose_submit(el=foo)`. See previous discussion in PR #131.

form.py: rename argument of choose_submit

---

.travis.yml
wait-for-httpbin.sh

Hopefully this will reduce the failure rate on Travis-CI.

.travis-ci.yml: basic back-off strategy when httpbin is down

---

docs/ChangeLog.rst
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

Closes #130.
The `nr` option allows us to choose which form to select if
multiple forms match the `selector`. Defaults to the first
matching form.
In addition, `*args` and `**kwargs` are no longer forwarded
to BeautifulSoup's `.select`.
---------------

stateful_browser.py: add nr option to select_form

---

README.rst
docs/external-resources.rst

The main README no longer seems like an appropriate place for
these references. We have the FAQ which discusses RoboBrowser
extensively, and I've added a "news archive" bullet in
`docs/external-resources.rst`.

README.rst: move "See also" section to docs

---

CONTRIBUTING.rst
docs/ChangeLog.rst
mechanicalsoup/__version__.py

The next release is expected to be v1.0.0. While in development,
the version will be reported as "1.0.0-dev".
Since I cannot upload to PyPI, I'm making this available to be merged after the upload is finished, as per the release checklist.

Prepare for next release

---

.travis.yml

This caches `$HOME/.cache/pip` in Travis builds.
Our Travis build time is often dominated by dependency installation,
so caching pip can speed up builds significantly.
The cache can be managed at:
https://travis-ci.org/MechanicalSoup/MechanicalSoup/caches

.travis.yml: enable the pip cache

---

.travis.yml

Closes #146.
Until we understand why flake8 is so slow in pypy environments
(to the point where it causes Travis to stall), do not run flake8
tests in these environments.
We do this by overriding the option specified in `setup.cfg` about
which files flake8 should ignore, telling it to instead ignore all
files. This is slightly hacky because a) we still want flake8 to
always be run by users and by all other environments and b) there
is no '--no-flake8' option.
We are still running flake8 tests in all standard python envs,
so there is no real loss of testing coverage.

.travis.yml: don't use flake8 in pypy environments

---

docs/ChangeLog.rst
mechanicalsoup/browser.py
tests/test_browser.py

Closes #165.
Since both `Browser._prepare_request` and `Browser._build_request` are
internal methods, we can replace them with a single `Browser._request`.
This new method is the same as `_build_request`, except that it calls
`self.Session.request` to prepare and send the request instead of doing
it in two separate steps.
Since `requests.Session.request` both prepares and sends the request,
it has an API that includes keywords for both actions. The keywords
are a superset of `requests.Request` (except for `hooks`, but since
MechanicalSoup did not expose the resulting Request object, I believe
the hooks could not be used).
As a result, the `kwargs` that can be passed to `Browser.submit` has
expanded to include keywords related to sending the request.

browser.py: refactor Browser.submit method

---

mechanicalsoup/browser.py
mechanicalsoup/stateful_browser.py

* Defaults to `self.get_current_page()` so that the default
behavior remains unchanged.
* Improve documentation of both `launch_browser` methods.

stateful_browser.py: add soup argument to launch_browser

---

mechanicalsoup/browser.py

Use coverage's "no cover" pragma on the else branch of browser.py
that is only ever covered in Python 2 versions.
Even though codecov.io synthesizes reports from all Travis builds
(which includes python 2.7), and therefore sees coverage of this
line, it might be confusing to any developers who are running
individual tests and are expecting 100% coverage.
It's not clear what is best in this situation, but I think that
favoring ease of development in the latest Python version is
preferable to tracking whether or not this line is covered.

browser.py: add "no cover" pragma for versioned code

---

tests/conftest.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py
tests/utils.py

We add a testing utils class `HttpbinWrapper`, which is simply
a drop-in replacement for the `httpbin` fixture that pytest-httpbin
provides.
This will allow us to write tests in the style of pytest-httpbin
until we can merge PR #164 into master.

Add pytest fixture to prepare for pytest-httpbin

---

mechanicalsoup/form.py
tests/test_form.py

Closes #180.
If a submit element exists without a name-attribute, then previously
`Form.choose_submit` would raise a KeyError when it loops over the
elements.
Instead, we should simply ignore any nameless submit element,
regardless of whether it is there because the html is malformed or
because that particular element is used for javascript, for example.

form.py: harden choose_submit against invalid html

---

mechanicalsoup/browser.py

One of the web servers I tried MechanicalSoup against leaves out the `Content-Type` on some HTML containing responses.
According to https://tools.ietf.org/html/rfc2616#section-7.2.1 
this is actually valid behavior and we are expected to guess if we so choose.
This changes `add_soup(response, soup_config)` to take a swag in that case.

Handles html entities that don't say they are html

---

mechanicalsoup/browser.py

Depending on the contents of the file (I think), Google Chrome may
display a file as text rather than html unless it has a .html
extension. In `launch_browser`, we typically want to look at the
rendered html of the page (otherwise we would just print the html
as text in the command line), so to ensure this happens we can
add a `.html` suffix to the temporary file.
NOTE: `launch_browser` started displaying the page contents in text for me recently after rendering the html for the same page in the past. I don't know if this is due to a different version of Chrome or due to changes in the contents of the html. Adding the `.html` suffix to the filename fixed this problem for me, but I'm not entirely sure it's the most appropriate solution.

browser.py: write temporary file with .html extension

---

docs/ChangeLog.rst
mechanicalsoup/utils.py
tests/test_utils.py

Closes #203.
The python documentation recommends to all developers that custom
exception classes should derive from `Exception` instead of
`BaseException`.
This change is not backwards compatible. Previously, a
`LinkNotFoundError` would pass through an `Exception` catch.
After this change, it would no longer pass through.

Derive LinkNotFoundError from Exception

---

tests/test_browser.py
tests/test_stateful_browser.py

Fixes #215.
There were three tests that were still accessing http://httpbin.org.
By switching these to use the `httpbin` pytest fixture, we no longer
require any network access.

Make sure all tests can be run offline

---

tests/test_stateful_browser.py
tests/utils.py

The new httpbin version has a JavaScript-enabled welcome page, not
suited for MechanicalSoup. Fortunately, the old version is still
available with a URL /legacy.
Use this URL, if available, for tests which need it.
Fixes #213.

Allow the testsuite to run on new httpbin versions

---

docs/ChangeLog.rst
mechanicalsoup/browser.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py
tests/utils.py

Improve consistency of query string construction between
MechanicalSoup and web browsers in edge cases where form elements
have duplicate *name*-attributes.
For example, if a form with the following is submitted:
```
<input name="key" value="val1" />
<input name="key" value="val2" />
```
Then the resulting query string will now be
```
key=val1&key=val2
```
instead of
```
key=val2
```
More detail
===========
Store data to be encoded in the query string in a list of 2-tuples
instead of a dictionary. In doing so, we allow for the possibility
of multiple form elements being submitted with the same name.
Surprisingly, this is legal HTML (though sometimes unintentional),
so we want to be as faithful as possible to how the query string for
such a form would be created in a real browser.
To do …

Rewrite `Browser._request` to handle repeated input elements

---

tests/test_form.py

Related to #207.
Tests that we can correctly choose between different but
identically named submit elements by using CSS selectors.

test_form.py: add test_choose_submit_from_selector

---

mechanicalsoup/form.py
tests/test_form.py

Since some button elements are submittable, it is important to
print them in the summary. We do not differentiate between button
types when printing since this is only a diagnostic method.

form.py: print button elements in print_summary

---

mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/test_form.py

Form construction and `select_form` will now raise a LinkNotFoundError
when passed a bs4.element.Tag _or_ a CSS selector that is not for a
`form` element.
Previously, this was enforced inconsistently, only raising when
`select_form` was passed an invalid bs4.element.Tag.

form.py: must construct forms from form elements

---

CONTRIBUTING.rst

* Distribute both Wheel and Source
* Add a step to test distribution on test.pypi.org
* Add explicit twine instructions (and drop setup.py alternative)
because Python recommends using it for uploads to PyPI.
Closes #225.
Instructions have been tested up to the official upload to PyPI.

CONTRIBUTING.rst: new packaging instructions

---

mechanicalsoup/browser.py
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/test_form.py

I ran into a site with forms including buttons of `type` "button" with `name` attributes. Because `Form.choose_submit()` was only removing `name` from buttons of `type` "submit", the values for the "button" buttons were being erroneously sent on POST, thereby breaking my submission. This patch fixes the issue, even when a submit button isn't explicitly chosen.
Note that all buttons that aren't of `type` "button" or "reset" function as "submit" in all major browsers and should therefore be choosable.

Remove `name` attribute from all unused buttons on form submit

---

tests/test_form.py

When a BeautifulSoup object is constructed from an html string,
it will standardize the html. In this case, since the input html
was just a raw `<form>`, it added `<html>` and `<body>` tags around it.
Since the `Form` ctor now demands that it is passed a `<form>` element,
we need to extract `<form>` from the object BeautifulSoup constructs
to pass to the `Form` ctor.
-----------------
Side question: The sanity check on `Form` being passed a `<form>` is in principle a good one, since I have seen plenty of errors that resulted from passing something that wasn't (or didn't even contain) a form to the `Form` ctor. But is it too restrictive? Should we expect that passing a `<html><body><form>...</form></body></html>` to `Form` should work? And if so, could we allow such a thing without also …

test_form.py: fix test_choose_submit_twice

---

mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/test_form.py

In 4e3fd3cdda9a, passing a bs4.element.Tag that was not a "form"
to the constructor of `Form` was escalated to a `LinkNotFoundError`.
Since this breaks backwards compatibility, we soften the error to
a deprecation warning (using the warnings library). In a future
version, this may become an error again.
However, `StatefulBrowser.select_form` has always raised an error
in this case since it began accepting a bs4.element.Tag in a5dec341,
so we continue to do so there.
Related to #228.

form.py: relax error to deprecation warning

---

mechanicalsoup/browser.py

We recommend using the StatefulBrowser class for most applications,
so say this in the Browser docstring.
Related to #189.

browser.py: suggest StatefulBrowser in docstring

---

docs/faq.rst

This FAQ shows users how to explicitly select the submit element
that they want to submit a form with. It address some confusion
demonstrated by issue #227.

faq.rst: add tip for choosing submits

---

mechanicalsoup/browser.py

This docstring note is a necessary (but probably not sufficient)
change to `Browser.submit` to prevent it from being used in an
inappropriate way from a `StatefulBrowser` instance.
See #230 and #233 for more info.

browser.py: add StatefulBrowser note in submit docstring

---

tests/test_form.py
tests/test_stateful_browser.py
tests/utils.py

CSS selectors in bs4 now return elements in page order, whereas
they did not previously.
This requires us to re-order some of our expected test output,
and to perform an order-independent comparison if tested with
a bs4 version before 4.7.0.
Tested and passing with bs4 4.6.0 and 4.7.1.
Closes #257.

Fix tests for bs4 4.7.0+

---

mechanicalsoup/browser.py

The tag types were being checked in two ways:
1. `tag.get("type", "").lower() == X`
2. `tag.get("type") is not None and tag.get("type").lower() == X`
Since these should be identical, change all to the first option,
which is simpler and faster.
This is a follow-up to #246.

browser.py: check tag type consistently

---

tests/test_stateful_browser.py

The `test_link_arg_regex` test was accidentally passing. By adding
another link to the test html, we can see that it was selecting the
first link instead of the link that matched the supplied regex.
This new version of the test fails, but it will be fixed by #256.
Also added a case for no arguments and reduced code duplication
by changing it to a parameterized test.
I'm not sure what way would be best to merge this in, since it should
come before #256 (to demonstrate the existing failure), but we probably
don't want the master branch to be failing for an extended period of time.
Any thoughts?

Improve `test_link_arg_*` tests

---

README.rst

Also, point to the bug in the new GitHub repository, the one we
pointed to is obsolete.

Mechanize {is -> was} incompatible with Python 3

---

mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

If you called the function with url_regex='/something' and not the
link argument, it would set the url_regex to None, and thus the result
would be not the one expected.
This is tested by the test fixed by #261.
(Followup on #256)

debug _find_link_internal and remove xfail on related test

---

docs/conf.py

* Automatically update the copyright date
* Add the "last updated" date
Locally, these changes will look like this:

Enhancement for dates in the documentation pages

---

docs/ChangeLog.rst
mechanicalsoup/browser.py
tests/test_browser.py

This is in regards to issue #250 
For the tests, I followed @moy 's train of thought : 
- they are basically a copy+paste without the creation of a temp file
- `assert value["doc"] == ""` checks that the response contains an empty file
Thought a different test definition was necessary, was I right to assume so ?
In `browser.py`, I changed the `continue` around [line 179](https://github.com/MechanicalSoup/MechanicalSoup/blob/685eb6e1396008a0b3881bea5bcc6b7119f61642/mechanicalsoup/browser.py#L179) to something similar to what has been done in `test__request_file` [here](https://github.com/MechanicalSoup/MechanicalSoup/blob/685eb6e1396008a0b3881bea5bcc6b7119f61642/tests/test_browser.py#L93)
There are 2 `Add no file input submit test` commits : the second one is simply a clean up of some …

Submit an empty file when leaving a file input blank

---

.travis.yml
setup.py

Add tests against python 3.7 in .travis.yml.
Note that we can no longer use the default dist, "trusty", because
python 3.7 requires an SSL package that is only available as of
xenial. See https://github.com/travis-ci/travis-ci/issues/9815.
On xenial, the PyPy packages have a different naming convention
(e.g. just `pypy` and `pypy2.7` don't exist), so we switch to the
naming convention for the most recent v6.0 PyPy release.
See https://travis-ci.community/t/pypy-2-7-on-xenial/889.

Officially support python 3.7

---

mechanicalsoup/__version__.py
setup.py

Fixes #239
Add code in order to concatenate the github logo raw link, to the
relative one presents in the readme.

Add github image link in the readme

---

mechanicalsoup/browser.py
tests/test_browser.py
tests/test_stateful_browser.py

Fixes #242.
Make MechanicalSoup behave as a real browser:
- only "multipart/form-data" enctype allow file sending
- forms without file inputs can now be sent as "multipart/form-data"
if specified.
- "application/x-www-form-urlencoded" is the default when enctype is wrong
or not specified
The added code uses a hack because of a lack in Requests
functionalities: Requests doesn't support forcing enctype yet, and
doesn't allow to submit using "multipart/data-form" enctype without
submitting files. So the best way we found to bypass this is to pass
an modified dict as files to Requests. This code could change in the
future if Requests implements a "force enctype" feature.

Add "enctype respecting" feature and tests

---

.travis.yml
setup.py

Python 3.4 has reached its end of life on March 18, 2019.
See https://www.python.org/dev/peps/pep-0429/.
More practically, lxml-4.4.0 requires python 3.5+, which causes our
CI for python 3.4 to fail.

Drop support for python 3.4

---

docs/ChangeLog.rst
examples/example.py
examples/expl_duck_duck_go.py
examples/expl_httpbin.py
mechanicalsoup/stateful_browser.py
tests/test_form.py
tests/test_stateful_browser.py

This superseeds #185 (which I'm keeping untouched for the record).
Essentially:
* No more getters in the recommended interface, just properties.
* Getters are kept with their old names, only for backward compatibility
* Properties are now used everywhere (examples, code, tests)
Each commit passes tests. PR best reviewed commit-by-commit, as it contains both small manual changes with batch search-and-replace.

Properties

---

.travis.yml

* `pypy` and `pypy3` now point to PyPy 7
* Test slower PyPy first to speed up the build
* `sudo` is no longer needed: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Upgrade PyPy

---

mechanicalsoup/form.py
tests/test_form.py

The `PendingDeprecationWarning` exception is suppressed by default,
which makes it not very helpful as a way to warn users about likely
incorrect usage. Switch to `FutureWarning`, which is not suppressed
by default.
Also fix a missing string formatting argument.
This would have helped to prevent the mistake made in #315.

form.py: improve warning in Form initialization

---

README.rst
examples/expl_qwant.py

Our DuckDuckGo example doesn't work anymore, probably due to an
anti-bot feature on DuckDuckGo. This introduces and promotes in
README.rst an example that actually works.
Unless we find a way to repair the DuckDuckGo example, we probably want to remove examples/expl_duck_duck_go.py completely instead of #318.
Cc: @dillonko

Example use of MechanicalSoup using Qwant

---

mechanicalsoup/form.py

Fix a tiny typo in the documentation explaining how to set a file type input. (The suggested syntax sets a function call to a value.)

Fix a tiny type to `set` documenation

---

mechanicalsoup/stateful_browser.py

E741 ambiguous variable name 'l'
Replace this short variable name with `link`.

stateful_browser.py: fix flake8 warning

---

README.rst

Relates to #340 (but doesn't fix it ;) )
I've left a link to the latest documentation in the badge, but the badge is in the contribution section of the README so it would make sense... Though people might still get on the wrong version of the doc. Well, we've reduced the risk :)

Link to the stable documentation, rather than the latest one

---

mechanicalsoup/browser.py
tests/test_browser.py

When we use mechanicalsoup, we sometimes want to verify a request before submitting it.
If you merge this pull request, the package will be able to provide a way for the package's users to review the request.
This is my first pull request for this project. Please let me know if I'm missing anything.

Add get_request_kwargs to check before requesting

---

mechanicalsoup/browser.py
tests/test_browser.py

We pass the form data to requests via `data` for POST methods, and
via `params` for GET methods. Therefore, we should be initializing
our data with the kwargs `data` or `params` respectively (whereas
previously we were initializing with `data` only).
Also added tests to check that we raise an exception when the kwargs
include a parameter that duplicates one of the args that we manually
set (i.e. `url` or `method`).

Improve handling of kwargs passed to Requests

---

.travis.yml
CONTRIBUTING.rst
README.rst
docs/conf.py
docs/introduction.rst
examples/example.py
mechanicalsoup/browser.py
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
requirements.txt
setup.cfg
setup.py
tests/test_stateful_browser.py
tests/utils.py

Fixes #310.
Also upgrades Python syntax with https://github.com/asottile/pyupgrade, removes the dependency on six, and removes `sudo` from `.travis.yml`, which is no longer needed: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Drop support for EOL Python 2.7

---

.travis.yml
tests/requirements.txt

Explicitly require pytest >= 3.1.0 in tests/requirements.txt, due to
the use of `pytest.param`.
This ensures a compatible local testing environment, and allows us to
remove the manual pytest upgrade for Travis-CI. (We also remove the
manual pytest-cov installation, because that is already handled by
the tests/requirements.txt file.)

Add pytest minimum version requirement

---

.travis.yml
docs/ChangeLog.rst
mechanicalsoup/browser.py
mechanicalsoup/form.py
setup.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py

This also allows us to replace `.format()` with f-strings.

Drop support for EOL Python 3.5

---

requirements.txt

* requests >= 2.22.0 [#282]
* beautifulsoup4 >= 4.7 [#244]
These versions are pretty old at this point, so there is little downside to bumping the minimum requirements, especially since they are well-motivated.

Bump minimum requirements

---

mechanicalsoup/form.py

This change requires bs4 4.7.0+ (since older versions of bs4 do not
follow the CSS selector spec as closely as SoupSieve does).
I think we should delay applying this patch, since a hard dependency
on bs4 4.7.0 is too restrictive right now, but I do think that the
resulting code is more compact and easier to read.

form.py: replace find_by_type with case-insensitive selectors

---

mechanicalsoup/browser.py
tests/test_browser.py
tests/utils.py

Hi,
Here is a PR for fixing #354, along with tests. Httpbin offers a testing endpoint defining encoding at the HTTP level, but not through a HTML tag (precisely the error initially described in #354). I did not find any testing endpoints to use for other cases ("no HTTP encoding, HTML one" and "both of them").
Best,

Use encoding from the HTTP request when no HTML encoding is specified

---

docs/conf.py
examples/example.py
examples/example_manual.py
examples/expl_duck_duck_go.py
examples/expl_google.py
examples/expl_httpbin.py
examples/expl_qwant.py
mechanicalsoup/__init__.py
mechanicalsoup/browser.py
mechanicalsoup/form.py
mechanicalsoup/stateful_browser.py
tests/setpath.py
tests/test_browser.py
tests/test_form.py
tests/test_stateful_browser.py
tests/test_utils.py
tests/utils.py

(This is not intended to be squashed; I can break it into two PRs if that's better)
* prereq: Sort and group all imports per PEP8 (isort)
* actual: submit_selected(): Referer fixes
Don't override a Referer field that a user passes in.
Note that since HTTP headers are case-insensitive, use requests'
CaseInsensitiveDict to handle this.
Futhermore, don't modify the caller's **kwargs, the caller should
assume we do not modify the submitted dict, so make a copy
first.
Do this in _merge_referer() helper function, as we anticipate needing
this in other functions when #362 is fixed.
Add a test for overriding Referers.
This was raised in https://github.com/MechanicalSoup/MechanicalSoup/issues/362#issuecomment-812921602

submit_selected(): Don't override user's Referer

---

docs/ChangeLog.rst
mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

Addresses #362: browser.follow_link() has no way to pass kwargs to requests
Accept keywords args in three ways:
bs4_kwargs	  Explicitly passed to Beautiful Soup, via find_link, &c.
requests_kwargs Passed to requests, via open_relative
**kwargs	  Excess args, merged with bs4_kwargs for backwards
compatibility
Adjust docstrings as appropriate.
Rename *args to *bs4_args to more clearly indicate that these positional
args go to the bs4 functions not to the requests functions.
Add tests:
test_download_link_nofile_bs4
passes args to BeautifulSoup via bs4_kwargs
test_download_link_nofile_excess
passes args to BeautifulSoup via excess **kwargs
test_follow_link_ua()
test_download_link_nofile_ua()
both of which pass in requests_kwargs that set the User-Agent header

stateful_browser: {follow,download}_link: Allow requests_kwargs

---

mechanicalsoup/browser.py
tests/test_browser.py

I noticed that MechanicalSoup is submitting the full local file path of the uploaded file to the server, while other browsers are only sending the filename. This behavior might leak more information to the server than the user is expecting.
I checked the [HTML Spec for "File Upload state"](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)) (I think that is the applicable reference to check?), and it says:
> Filenames must not contain path components, even in the case that a user has selected an entire directory hierarchy or multiple files with the same name from different directories. Path components, for the purposes of the File Upload state, are those parts of filenames that are separated by U+005C REVERSE SOLIDUS character (\\) characters.
This PR aims to …

stop submitting absolute file path for file uploads

---

.github/workflows/python-package.yml

Added the python-package.yml file to use the github actions CI instead of travis (see #357),
like in the travis.yml file, the github actions file creates environment for different python versions, install dependencies and run pytest. Codecov is triggered with the last job.

Switch to Github Actions

---

.github/workflows/python-package.yml

The codecov-action@v2 does not automatically generate the XML coverage
report (unlike v1), so we need to generate it ourselves by running:
coverage xml
This generates a `coverage.xml` file from the binary `.coverage` file
written by pytest. We will now also fail the CI if the codecov upload
fails, to help catch issues like this more easily.
Note that we could have added `--cov-report=xml` to the pytest options
in `setup.cfg`, but the XML coverage file is not generally useful to
devs running pytest locally. We also could have added it to the pytest
invocation in the test workflow, but we would have needed to repeat it
twice due to the pypy-specific step.

Fix coverage uploading with codecov-action@v2

---

tests/requirements.txt

In the continuous integration workflow, when pytest runs and calls httpbin, there was an incompatibility issue because httpbin imports a class called 'BaseResponse' from the werkzeug library. Werkzeug recently released a new version (2.1.0) removing this class because it's deprecated. Adding the condition `werkzeug < 2.1.0` in the tests/requierements.txt file will temporarly solve the problem.
I requested a PR in the httpbin library, but this little modification will avoid issues in the workflow.

Add werkzeug version in tests/requirements.txt file

---

tests/test_stateful_browser.py

Use the compatibility function open_legacy_httpbin in test_follow_link_ua so that it works with newer versions of httpbin.

Fix test_follow_link_ua to work with newer httpbin

---

tests/utils.py

That makes it a better drop-in replacement for browser.open

Return response in open_legacy_httpbin

---

mechanicalsoup/stateful_browser.py
tests/test_stateful_browser.py

According to the [HTML spec](https://html.spec.whatwg.org/multipage/forms.html#category-listed), a list of elements (button, input, object, output, select, textarea) can have a form attribute, so they can be placed anywhere on the page and be associated with a form without being a child of it. MechanicalSoup don't support this, so I added a code that scraps the page and finds all associated element of a selected form using beautiful soup methods.

Support associated elements with a form

---

tests/requirements.txt

The 5.0.0 release of flake8 is incompatible with the most recent version of the pytest-flake8 plugin. Pin to an earlier version until a fix is released.
See https://github.com/tholo/pytest-flake8/issues/87.

tests/requirements.txt: pin to flake8 < 5.0.0

---

setup.py
tests/test_browser.py
tests/test_stateful_browser.py

* Always use context managers for file resources. Fixes rule py/file-not-closed.
* Don't assign a function return value to a variable when asserting that the function will raise an Exception. Fixes rule py/multiple-definition.

Fix CodeQL warnings

---

.github/workflows/codeql.yml
.github/workflows/python-package.yml
.github/workflows/python-publish.yml

The `ubuntu-latest` runner label recently switched from `ubuntu-20.04` to `ubuntu-22.04`. This caused our python 3.6 tests to fail, because the new image only provides python 3.7+.
Having the environment silently change between different Action runs with the same commit is undesirable, so we should select a versioned runner label instead of `ubuntu-latest`. We select `ubuntu-20.04` because we still want to support python 3.6 for now.
See https://github.com/actions/runner-images/issues/6399 for details.

Switch Actions from ubuntu-latest to ubuntu-20.04

---

tests/test_stateful_browser.py

Add a test for when `_find_link_internal` is passed a `bs4.element.Tag` as the `link` argument. Called via `follow_link`.

Improve test coverage of StatefulBrowser._find_link_internal

---

requirements.txt

This was done by synk in 914958de0cbc4ce3133a54efc73d2cffc43752bc to avoid vulnerability, but for some reasons it was not done in the main requirements.txt.

Pin certifi to 2022.12.7 in production requirements.txt

---

.github/workflows/python-package.yml

This change in codecov was due to rate limiting of their global upload token.
Updated to v4 of the codecov action.

Fix codecov uploads after test workflow

---

.github/workflows/python-package.yml
docs/ChangeLog.rst
setup.py

These versions reached end of life in Dec 2021 and Jun 2023 respectively. To address recent security vulnerabilities, we need to update to newer versions of dependencies that no longer support these EOL versions (e.g. #434, while this is a dev dependency issue only, it's probably time to update the production requirements as well).

Remove support for python 3.6 and 3.7

---

tests/requirements.txt

Pin werkzeug >= 3.0.3 to address all active security vulnerabilities. This is possible now that httpbin has been forked into the PSF org, and a new version has been released (v0.10.0) that is compatible with new werkzeug versions.
Closes #431.

dev: fix werkzeug vulnerabilities

---

.github/workflows/python-package.yml
setup.py
tests/requirements.txt

* Remove support for python 3.8 (EOL 2024-10-07)
* Add support for python 3.12 and 3.13
There is a new maintainer for pytest-flake8 (see
https://github.com/tholo/pytest-flake8/issues/98), which allows us to migrate to the newest version of flake8.

Update python version support

---

.github/workflows/codeql.yml
.github/workflows/python-package.yml
.github/workflows/python-publish.yml

The ubuntu-20.04 image is deprecated and will be removed on 2025-04-01.

GHA: update runner image from ubuntu 20.04 to 24.04

---

tests/test_stateful_browser.py

Fixes #450.
The HTML parser in libxml2 2.14 is more strict about closing textarea elements.
Thanks to @doko42 for reporting this issue.

test_stateful_browser.py: fix unclosed textarea element
